In [7]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.optimizers import Nadam
from keras.callbacks import EarlyStopping
import numpy as np
from os.path import join
from pickle import load
import shutil
from sklearn.metrics import mean_squared_error
import keras.backend as K
import random
import os
import datetime

def seed_everything(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    tf.random.set_seed(seed)

print(tf.__version__)
print(keras.__version__)

# Model 생성, compile
modelType = 'Dense'
def create_model():

    model = tf.keras.models.Sequential([
    tf.keras.layers.InputLayer(input_shape=(4242,)),
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(6000, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(4000, activation='relu'),  
    tf.keras.layers.Dense(303, activation='linear'),  
    ])

    return model
model = create_model().summury()

learningRate = 0.001 # 세번째 실험
patience = 10
myoptim=Nadam(learning_rate=learningRate, beta_1=0.9, beta_2=0.999, epsilon=1e-07, decay=0.0)
early_stopping = EarlyStopping(monitor='val_loss',patience = patience, mode='min') # 일단은 적당히 epoch 주고 돌리기

# 원래의 범위로 값 평가하기
# 원래 정확도 복구해서 tensorboard에 기록하기
def rescaled_RMSE(y_true, y_pred):
    y_true = tf.reshape(tf.squeeze(y_true), [-1,3])
    y_pred = tf.reshape(tf.squeeze(y_pred), [-1,3])
    y_true = (y_true - K.constant(load_scaler4Y_moBHWT.min_)) / K.constant(load_scaler4Y_moBHWT.scale_)
    y_pred = (y_pred - K.constant(load_scaler4Y_moBHWT.min_)) / K.constant(load_scaler4Y_moBHWT.scale_)
    # default is RMSE, squaredbool, default=True If True returns MSE value, if False returns RMSE value.
    # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html
    rescaled_RMSE = 100 * K.sqrt(K.mean(K.square(y_pred - y_true))) / (K.max(y_true) - K.min(y_true))
    print(f"\nUsing {numFold} fold scaler")
    return rescaled_RMSE

def X_Axis_RMSE(y_true, y_pred):
    NumAxis = 0
    y_true = tf.reshape(tf.squeeze(y_true), [-1,3])[NumAxis]
    y_pred = tf.reshape(tf.squeeze(y_pred), [-1,3])[NumAxis]
    print(y_true.shape)
    y_true = (y_true - K.constant(load_scaler4Y_moBHWT.min_[NumAxis])) / K.constant(load_scaler4Y_moBHWT.scale_[NumAxis])
    y_pred = (y_pred - K.constant(load_scaler4Y_moBHWT.min_[NumAxis])) / K.constant(load_scaler4Y_moBHWT.scale_[NumAxis])
    # default is RMSE, squaredbool, default=True If True returns MSE value, if False returns RMSE value.
    # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html
    X_Axis_RMSE = 100 * K.sqrt(K.mean(K.square(y_pred - y_true))) / (K.max(y_true) - K.min(y_true))
    print(f"\nUsing {numFold} fold scaler")
    return X_Axis_RMSE
    
def Y_Axis_RMSE(y_true, y_pred):
    NumAxis = 1
    y_true = tf.reshape(tf.squeeze(y_true), [-1,3])[NumAxis]
    y_pred = tf.reshape(tf.squeeze(y_pred), [-1,3])[NumAxis]
    print(y_true.shape)
    y_true = (y_true - K.constant(load_scaler4Y_moBHWT.min_[NumAxis])) / K.constant(load_scaler4Y_moBHWT.scale_[NumAxis])
    y_pred = (y_pred - K.constant(load_scaler4Y_moBHWT.min_[NumAxis])) / K.constant(load_scaler4Y_moBHWT.scale_[NumAxis])
    # default is RMSE, squaredbool, default=True If True returns MSE value, if False returns RMSE value.
    # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html
    Y_Axis_RMSE = 100 * K.sqrt(K.mean(K.square(y_pred - y_true))) / (K.max(y_true) - K.min(y_true))
    print(f"\nUsing {numFold} fold scaler")
    return Y_Axis_RMSE

def Z_Axis_RMSE(y_true, y_pred):
    NumAxis = 2
    y_true = tf.reshape(tf.squeeze(y_true), [-1,3])[NumAxis]
    y_pred = tf.reshape(tf.squeeze(y_pred), [-1,3])[NumAxis]
    print(y_true.shape)
    y_true = (y_true - K.constant(load_scaler4Y_moBHWT.min_[NumAxis])) / K.constant(load_scaler4Y_moBHWT.scale_[NumAxis])
    y_pred = (y_pred - K.constant(load_scaler4Y_moBHWT.min_[NumAxis])) / K.constant(load_scaler4Y_moBHWT.scale_[NumAxis])
    # default is RMSE, squaredbool, default=True If True returns MSE value, if False returns RMSE value.
    # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html
    Z_Axis_RMSE = 100 * K.sqrt(K.mean(K.square(y_pred - y_true))) / (K.max(y_true) - K.min(y_true))
    print(f"\nUsing {numFold} fold scaler")
    return Z_Axis_RMSE



# 학습 조건 저장하기
config = dict()
config["model"] = modelType
config['patience'] = patience

# 데이터 셋 준비
# 데이터 셋 준비
dataSetDir = r'Z:\PROJECTS\iwalqq\Data\V3D\Output\IMU Deep Learning\Data\20220325_raw_byDeepak_csv\INC_ByStep\INC_ByZero\Included_checked\SAVE_dataSet'
scalerDir  = r'Z:\PROJECTS\iwalqq\Data\V3D\Output\IMU Deep Learning\Data\20220325_raw_byDeepak_csv\INC_ByStep\INC_ByZero\Included_checked\SAVE_fittedScaler'

# 준비된 K-fold data iterations
time = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

SaveModelDir = 'SavedModel'
# shutil.rmtree('./logs', ignore_errors=True) # 삭제는 신중ㅎ히
# tensorboard 동작시키는 법 : tensorboard --logdir logs/fit


epochs = 1
for numFold in range(0,5): # 5-fold crossvalidation
    # 각 fold 별로 별도로 표기하기
    log_dir = "logs/fit/" + str(numFold) + '_fold_' + time
    tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)
    print(f"Num of Fold: {numFold}")
    # 데이터 불러오기
    # 모든 데이터는 scaled된 데이터임!
    load_train = np.load(join(dataSetDir,f"{numFold}_fold_final_train.npz"))
    load_test = np.load(join(dataSetDir,f"{numFold}_fold_final_test.npz"))
    print(f'loaded Train shape: {load_train["final_X_train"].shape}, {load_train["final_Y_angle_train"].shape}, {load_train["final_Y_moBHWT_train"].shape}')
    print(f'loaded Test shape: {load_test["final_X_test"].shape}, {load_test["final_Y_angle_test"].shape}, {load_test["final_Y_moBHWT_test"].shape}')
    # sclaer 불러오기
    # Here scaler is MinMaxScaler!
    load_scaler4X = load(open(join(scalerDir,f"{numFold}_fold_scaler4X.pkl"), 'rb'))
    load_scaler4Y_angle = load(open(join(scalerDir,f"{numFold}_fold_scaler4Y_angle.pkl"), 'rb'))
    load_scaler4Y_moBHWT = load(open(join(scalerDir,f"{numFold}_fold_scaler4Y_moBHWT.pkl"), 'rb'))

    # https://wandb.ai/sauravm/Optimizers/reports/How-to-Compare-Keras-Optimizers-in-Tensorflow--VmlldzoxNjU1OTA4
    # Nadam을 선택한 이유
    model = create_model()
    model.compile(optimizer=myoptim,
              loss='mean_absolute_error',
              metrics=[rescaled_RMSE, X_Axis_RMSE, Y_Axis_RMSE, Z_Axis_RMSE])
    # 차원 축소
    X_train = np.squeeze(load_train["final_X_train"], axis=2)
    Y_train = np.squeeze(load_train["final_Y_moBHWT_train"], axis=2)

    X_test = np.squeeze(load_test["final_X_test"], axis=2)
    Y_test = np.squeeze(load_test["final_Y_moBHWT_test"], axis=2)

    # 요건 나중에... [early_stopping,]
    history = model.fit(X_train, Y_train, validation_data=(X_test,Y_test), epochs=epochs, callbacks=[tensorboard_callback])

    # 모델은 확실해지면 저장하기
    # model.save(join(SaveModelDir,f"{numFold}_fold_my_model_"+time))


2.8.0
2.8.0
Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_4 (Flatten)         (None, 4242)              0         
                                                                 
 dense_12 (Dense)            (None, 6000)              25458000  
                                                                 
 dropout_4 (Dropout)         (None, 6000)              0         
                                                                 
 dense_13 (Dense)            (None, 4000)              24004000  
                                                                 
 dense_14 (Dense)            (None, 303)               1212303   
                                                                 
Total params: 50,674,303
Trainable params: 50,674,303
Non-trainable params: 0
_________________________________________________________________
Num of Fold: 0
loaded Train sh

KeyboardInterrupt: 

# 배운 것!

In [ ]:
y_true = (y_true - K.constant(load_scaler4Y_angle.min_)) / K.constant(load_scaler4Y_angle.scale_)
y_pred = (y_pred - K.constant(load_scaler4Y_angle.min_)) / K.constant(load_scaler4Y_angle.scale_)

In [ ]:
# https://stackoverflow.com/questions/55857212/scaling-back-data-in-customized-keras-training-loss-function
from sklearn.preprocessing import MinMaxScaler
import numpy as np

data = np.array([[-1, 2], [-0.5, 6], [0, 10], [1, 18]])
print('data:\n',data)
scaler = MinMaxScaler()
data_trans = scaler.fit_transform(data)
print('transform:\n',data_trans)

data_inverse = (data_trans - scaler.min_)/scaler.scale_
print('inverse transform:\n',data_inverse)


In [ ]:
scaler.inverse_transform(data_trans)

In [ ]:
scaler.scale_

In [ ]:
scaler.min_

In [31]:
import tensorflow as tf
logits = tf.random.uniform(([50,1]))
print(logits)
print(tf.reshape(logits,shape=[10,5]))

tf.Tensor(
[[0.09092975]
 [0.12411916]
 [0.11097777]
 [0.90343535]
 [0.65863633]
 [0.5038903 ]
 [0.81531835]
 [0.11922765]
 [0.44267535]
 [0.12487292]
 [0.25096822]
 [0.01589823]
 [0.45424676]
 [0.9813316 ]
 [0.64427793]
 [0.13936126]
 [0.7115203 ]
 [0.03113258]
 [0.37205803]
 [0.5225203 ]
 [0.83543   ]
 [0.18276966]
 [0.5997149 ]
 [0.87808084]
 [0.55225885]
 [0.0841701 ]
 [0.543236  ]
 [0.43449676]
 [0.66344714]
 [0.4394734 ]
 [0.4461223 ]
 [0.75619256]
 [0.96090126]
 [0.82392764]
 [0.57704854]
 [0.7458937 ]
 [0.02869189]
 [0.9994967 ]
 [0.1574409 ]
 [0.5164174 ]
 [0.37056577]
 [0.26939178]
 [0.9467038 ]
 [0.00451362]
 [0.15430284]
 [0.64233613]
 [0.52080226]
 [0.05968118]
 [0.6821805 ]
 [0.1590873 ]], shape=(50, 1), dtype=float32)
tf.Tensor(
[[0.09092975 0.12411916 0.11097777 0.90343535 0.65863633]
 [0.5038903  0.81531835 0.11922765 0.44267535 0.12487292]
 [0.25096822 0.01589823 0.45424676 0.9813316  0.64427793]
 [0.13936126 0.7115203  0.03113258 0.37205803 0.5225203 ]
 [0.83543    0

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.optimizers import Nadam
from keras.callbacks import EarlyStopping
import numpy as np
from os.path import join
from pickle import load
import shutil
from sklearn.metrics import mean_squared_error
import keras.backend as K

import datetime
scalerDir  = r'Z:\PROJECTS\iwalqq\Data\V3D\Output\IMU Deep Learning\Data\20220325_raw_byDeepak_csv\INC_ByStep\INC_ByZero\Included_checked\SAVE_fittedScaler'
load_scaler4Y_moBHWT = load(open(join(scalerDir,f"{numFold}_fold_scaler4Y_moBHWT.pkl"), 'rb'))

NameError: name 'numFold' is not defined